In [1]:
import pandas as pd
df = pd.read_csv('../data/raw/Medicare_Provider_Util_Payment_PUF_CY2023.csv')

/var/folders/j3/yz8yx0vd45qfg3gz7ggpgxhc0000gn/T/ipykernel_87685/1596799701.py:2: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/raw/Medicare_Provider_Util_Payment_PUF_CY2023.csv')

In [2]:
df.head()

,Rndrng_NPI,Rndrng_Prvdr_Last_Org_Name,Rndrng_Prvdr_First_Name,Rndrng_Prvdr_MI,Rndrng_Prvdr_Crdntls,Rndrng_Prvdr_Ent_Cd,Rndrng_Prvdr_St1,Rndrng_Prvdr_St2,Rndrng_Prvdr_City,Rndrng_Prvdr_State_Abrvtn,...,HCPCS_Desc,HCPCS_Drug_Ind,Place_Of_Srvc,Tot_Benes,Tot_Srvcs,Tot_Bene_Day_Srvcs,Avg_Sbmtd_Chrg,Avg_Mdcr_Alowd_Amt,Avg_Mdcr_Pymt_Amt,Avg_Mdcr_Stdzd_Amt
0,1003000126,Enkeshafi,Ardalan,NaN,M.D.,I,6410 Rockledge Dr Ste 304,NaN,Bethesda,MD,...,Initial hospital care with straightforward or ...,N,F,12,12.0,12,250.226667,89.062500,60.312500,54.669167
1,1003000126,Enkeshafi,Ardalan,NaN,M.D.,I,6410 Rockledge Dr Ste 304,NaN,Bethesda,MD,...,Initial hospital care with straightforward or ...,N,F,22,22.0,22,318.581818,130.312727,99.380000,98.429545
2,1003000126,Enkeshafi,Ardalan,NaN,M.D.,I,6410 Rockledge Dr Ste 304,NaN,Bethesda,MD,...,Subsequent hospital care with straightforward ...,N,F,76,127.0,127,95.732283,54.820157,43.557323,38.748661
3,1003000126,Enkeshafi,Ardalan,NaN,M.D.,I,6410 Rockledge Dr Ste 304,NaN,Bethesda,MD,...,Subsequent hospital care with moderate levelof...,N,F,180,341.0,341,194.441525,86.840762,69.086422,61.812258
4,1003000126,Enkeshafi,Ardalan,NaN,M.D.,I,6410 Rockledge Dr Ste 304,NaN,Bethesda,MD,...,Subsequent hospital care with moderate levelof...,N,F,53,79.0,79,251.454051,127.915190,100.943165,92.409114

In [4]:
df.shape

(9660647, 28)

In [5]:
df.columns

Index(['Rndrng_NPI', 'Rndrng_Prvdr_Last_Org_Name', 'Rndrng_Prvdr_First_Name',
       'Rndrng_Prvdr_MI', 'Rndrng_Prvdr_Crdntls', 'Rndrng_Prvdr_Ent_Cd',
       'Rndrng_Prvdr_St1', 'Rndrng_Prvdr_St2', 'Rndrng_Prvdr_City',
       'Rndrng_Prvdr_State_Abrvtn', 'Rndrng_Prvdr_State_FIPS',
       'Rndrng_Prvdr_Zip5', 'Rndrng_Prvdr_RUCA', 'Rndrng_Prvdr_RUCA_Desc',
       'Rndrng_Prvdr_Cntry', 'Rndrng_Prvdr_Type',
       'Rndrng_Prvdr_Mdcr_Prtcptg_Ind', 'HCPCS_Cd', 'HCPCS_Desc',
       'HCPCS_Drug_Ind', 'Place_Of_Srvc', 'Tot_Benes', 'Tot_Srvcs',
       'Tot_Bene_Day_Srvcs', 'Avg_Sbmtd_Chrg', 'Avg_Mdcr_Alowd_Amt',
       'Avg_Mdcr_Pymt_Amt', 'Avg_Mdcr_Stdzd_Amt'],
      dtype='object')

In [6]:
df.describe()

,Rndrng_NPI,Rndrng_Prvdr_RUCA,Tot_Benes,Tot_Srvcs,Tot_Bene_Day_Srvcs,Avg_Sbmtd_Chrg,Avg_Mdcr_Alowd_Amt,Avg_Mdcr_Pymt_Amt,Avg_Mdcr_Stdzd_Amt
count,9.660647e+06,9.653047e+06,9.660647e+06,9.660647e+06,9.660647e+06,9.660647e+06,9.660647e+06,9.660647e+06,9.660647e+06
mean,1.499464e+09,1.563976e+00,8.537118e+01,2.738522e+02,1.364925e+02,4.168288e+02,1.061070e+02,8.299084e+01,8.237403e+01
std,2.877096e+08,3.352656e+00,1.354371e+03,6.814589e+03,2.185786e+03,1.433275e+03,3.223192e+02,2.570740e+02,2.581384e+02
min,1.003000e+09,1.000000e+00,1.100000e+01,5.500000e+00,1.100000e+01,5.000000e-05,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.245948e+09,1.000000e+00,1.700000e+01,2.100000e+01,2.000000e+01,7.199000e+01,2.699469e+01,2.084682e+01,1.993000e+01
50%,1.497947e+09,1.000000e+00,3.200000e+01,4.300000e+01,4.000000e+01,1.750000e+02,7.137669e+01,5.310217e+01,5.362529e+01
75%,1.740786e+09,1.000000e+00,7.100000e+01,1.160000e+02,1.030000e+02,3.560000e+02,1.221174e+02,9.201797e+01,9.232525e+01
max,1.993000e+09,9.900000e+01,8.704860e+05,5.208424e+06,1.778281e+06,9.999999e+04,5.279404e+04,4.205952e+04,4.222933e+04

In [7]:
# Just show 3 columns to start
df[['Rndrng_Prvdr_Type', 'Avg_Sbmtd_Chrg', 'Avg_Mdcr_Pymt_Amt']].head(10)

  Rndrng_Prvdr_Type  Avg_Sbmtd_Chrg  Avg_Mdcr_Pymt_Amt
0       Hospitalist      250.226667          60.312500
1       Hospitalist      318.581818          99.380000
2       Hospitalist       95.732283          43.557323
3       Hospitalist      194.441525          69.086422
4       Hospitalist      251.454051         100.943165
5       Hospitalist      181.606154          68.387692
6       Hospitalist      278.034154          99.888359
7         Pathology      115.000000           8.873437
8         Pathology      170.000000          27.654756
9         Pathology       88.000000          20.885919

In [13]:
df.columns

Index(['Rndrng_NPI', 'Rndrng_Prvdr_Last_Org_Name', 'Rndrng_Prvdr_First_Name',
       'Rndrng_Prvdr_MI', 'Rndrng_Prvdr_Crdntls', 'Rndrng_Prvdr_Ent_Cd',
       'Rndrng_Prvdr_St1', 'Rndrng_Prvdr_St2', 'Rndrng_Prvdr_City',
       'Rndrng_Prvdr_State_Abrvtn', 'Rndrng_Prvdr_State_FIPS',
       'Rndrng_Prvdr_Zip5', 'Rndrng_Prvdr_RUCA', 'Rndrng_Prvdr_RUCA_Desc',
       'Rndrng_Prvdr_Cntry', 'Rndrng_Prvdr_Type',
       'Rndrng_Prvdr_Mdcr_Prtcptg_Ind', 'HCPCS_Cd', 'HCPCS_Desc',
       'HCPCS_Drug_Ind', 'Place_Of_Srvc', 'Tot_Benes', 'Tot_Srvcs',
       'Tot_Bene_Day_Srvcs', 'Avg_Sbmtd_Chrg', 'Avg_Mdcr_Alowd_Amt',
       'Avg_Mdcr_Pymt_Amt', 'Avg_Mdcr_Stdzd_Amt', 'charge_to_payment_ratio'],
      dtype='object')

In [16]:
df.columns = df.columns.str.strip()  # remove leading/trailing spaces

In [18]:
df['charge_to_payment_ratio'] = df['Avg_Sbmtd_Chrg'] / (df['Avg_Mdcr_Pymt_Amt'] + 1)

In [19]:
df[['Rndrng_Prvdr_Type', 'Avg_Sbmtd_Chrg', 'Avg_Mdcr_Pymt_Amt', 'charge_to_payment_ratio']].head(10)

,Rndrng_Prvdr_Type,Avg_Sbmtd_Chrg,Avg_Mdcr_Pymt_Amt,charge_to_payment_ratio
0,Hospitalist,250.226667,60.312500,4.081169
1,Hospitalist,318.581818,99.380000,3.173758
2,Hospitalist,95.732283,43.557323,2.148520
3,Hospitalist,194.441525,69.086422,2.774311
4,Hospitalist,251.454051,100.943165,2.466610
5,Hospitalist,181.606154,68.387692,2.617268
6,Hospitalist,278.034154,99.888359,2.755860
7,Pathology,115.000000,8.873437,11.647413
8,Pathology,170.000000,27.654756,5.932698
9,Pathology,88.000000,20.885919,4.020850

In [20]:
df[['Rndrng_Prvdr_State_FIPS', 'Rndrng_Prvdr_Zip5', 'Rndrng_Prvdr_RUCA', 'Rndrng_Prvdr_RUCA_Desc', 'Rndrng_Prvdr_Cntry', 'Rndrng_Prvdr_Type', 'Rndrng_Prvdr_Mdcr_Prtcptg_Ind', 'HCPCS_Cd']]

,Rndrng_Prvdr_State_FIPS,Rndrng_Prvdr_Zip5,Rndrng_Prvdr_RUCA,Rndrng_Prvdr_RUCA_Desc,Rndrng_Prvdr_Cntry,Rndrng_Prvdr_Type,Rndrng_Prvdr_Mdcr_Prtcptg_Ind,HCPCS_Cd
0,24,20817,1.0,Metropolitan area core: primary flow within an...,US,Hospitalist,Y,99221
1,24,20817,1.0,Metropolitan area core: primary flow within an...,US,Hospitalist,Y,99222
2,24,20817,1.0,Metropolitan area core: primary flow within an...,US,Hospitalist,Y,99231
3,24,20817,1.0,Metropolitan area core: primary flow within an...,US,Hospitalist,Y,99232
4,24,20817,1.0,Metropolitan area core: primary flow within an...,US,Hospitalist,Y,99233
...,...,...,...,...,...,...,...,...
9660642,53,98101,1.0,Metropolitan area core: primary flow within an...,US,Otolaryngology,Y,99214
9660643,51,23227,1.0,Metropolitan area core: primary flow within an...,US,Internal Medicine,Y,99223
9660644,51,23227,1.0,Metropolitan area core: primary flow within an...,US,Internal Medicine,Y,99232
9660645,51,23227,1.0,Metropolitan area core: primary flow within an...,US,Internal Medicine,Y,99233
9660646,51,23227,1.0,Metropolitan area core: primary flow within an...,US,Internal Medicine,Y,99239